version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: django
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: django-debug-toolbar
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: ipython
    versions:
    - ">= 7.a"
    - "< 8"
  - dependency-name: pytest
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: whitenoise
    versions:
    - ">= 4.a"
    - "< 5"
